"""
Django settings for lasDB project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import random, string

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#################################################################################################################
# Umgebungsvariablen:                                                                                           #
#################################################################################################################
# LASDB_DEBUG = "False"                                     (Default: "True")                                   #
# LASDB_SECRET_KEY = Benutze: https://www.miniwebtool.com/django-secret-key-generator/                          #
# LASDB_STATIC_ROOT = "/var/www/example.com/static/"        (Default: None)                                     #
# LASDB_STATIC_URL = "/static/"                             (Default: "/static/")                               #
# LASDB_PRIVATE_MEDIA = "/private-media/"                   (Default: "/private-media/")                        #
# django-private-storage:                                                                                       #
# LASDB_PRIVATE_STORAGE_ROOT = '/'                          (Default: '/')                                      #
# LASDB_PRIVATE_STORAGE_AUTH_FUNCTION = 'private_storage.permissions.allow_authenticated'                       #
# LASDB_PRIVATE_STORAGE_SERVER = 'nginx'                    (Default: 'django')                                 #
# LASDB_PRIVATE_STORAGE_INTERNAL_URL = '/private-x-accel-redirect/'                                             #
# Datenbank:                                                                                                    #
# LASDB_DB="django.db.backends.postgresql"                  (Default: "django.db.backends.sqlite3")             #
# LASDB_DB_NAME="LasDB"                                     (Default: os.path.join(BASE_DIR, 'db.sqlite3'))     #
# LASDB_DB_USER="user"                                      (Default: None)                                     #
# LASDB_DB_PASSWORD="passwort"                              (Default: None)                                     #
# LASDB_DB_HOST="postgresql://localhost"                    (Default: None)                                     #
# LASDB_DB_PORT="5433"                                      (Default: None)                                     #
#################################################################################################################

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9yg63qqxtxh@yo!e(j486y8pfnej_!ru1^#%5$#-#rm%-++2iz'

# SECURITY WARNING: don't run with debug turned on in production!
if 'LASDB_DEBUG' in os.environ and (os.environ['LASDB_DEBUG'] == 'False' or os.environ['LASDB_DEBUG'] is False):
    DEBUG = False
else:
    DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]', '.dioe.at']

ALLOWED_SETTINGS_IN_TEMPLATES = ("CACH_RANDOM")

CACH_RANDOM = ''.join(random.SystemRandom().choice(string.ascii_lowercase + string.digits) for i in range(8))

LASDB_APPLIST = ['db']
LASDB_MAXVERWEISE = 50

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'private_storage',
    'hcbDiagram',
    'db',
    'vue',
    'webpack_loader',
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'lasDB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'lasDB', 'templates'), os.path.join(BASE_DIR, 'vue', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lasDB.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Umgebungsvariablen:
if 'LASDB_SECRET_KEY' in os.environ:
    SECRET_KEY = os.environ['LASDB_SECRET_KEY']

if 'LASDB_DB' in os.environ and os.environ['LASDB_DB']:
    DATABASES['default']['ENGINE'] = os.environ['LASDB_DB']
    if 'LASDB_DB_NAME' in os.environ:
        DATABASES['default']['DBNAME'] = os.environ['LASDB_DB_NAME']
        DATABASES['default']['NAME'] = os.environ['LASDB_DB_NAME']
    if 'LASDB_DB_USER' in os.environ:
        DATABASES['default']['USER'] = os.environ['LASDB_DB_USER']
    if 'LASDB_DB_PASSWORD' in os.environ:
        DATABASES['default']['PASSWORD'] = os.environ['LASDB_DB_PASSWORD']
    if 'LASDB_DB_HOST' in os.environ:
        DATABASES['default']['HOST'] = os.environ['LASDB_DB_HOST']
    if 'LASDB_DB_PORT' in os.environ:
        DATABASES['default']['PORT'] = os.environ['LASDB_DB_PORT']

# print(DATABASES)

FILE_UPLOAD_PERMISSIONS = 0o644

PRIVATE_STORAGE_ROOT = '/'
PRIVATE_STORAGE_AUTH_FUNCTION = 'private_storage.permissions.allow_authenticated'
PRIVATE_STORAGE_SERVER = 'django'
PRIVATE_STORAGE_INTERNAL_URL = '/private-x-accel-redirect/'
if 'LASDB_PRIVATE_STORAGE_ROOT' in os.environ:
    PRIVATE_STORAGE_ROOT = os.environ['LASDB_PRIVATE_STORAGE_ROOT']
if 'LASDB_PRIVATE_STORAGE_AUTH_FUNCTION' in os.environ:
    PRIVATE_STORAGE_AUTH_FUNCTION = os.environ['LASDB_PRIVATE_STORAGE_AUTH_FUNCTION']
if 'LASDB_PRIVATE_STORAGE_SERVER' in os.environ:
    PRIVATE_STORAGE_SERVER = os.environ['LASDB_PRIVATE_STORAGE_SERVER']
if 'LASDB_PRIVATE_STORAGE_INTERNAL_URL' in os.environ:
    PRIVATE_STORAGE_INTERNAL_URL = os.environ['LASDB_PRIVATE_STORAGE_INTERNAL_URL']

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'de-DE'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = False
USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
PRIVATE_MEDIA = '/private-media/'

# Umgebungsvariablen:
if 'LASDB_PRIVATE_MEDIA' in os.environ and os.environ['LASDB_PRIVATE_MEDIA']:
    PRIVATE_MEDIA = os.environ['LASDB_PRIVATE_MEDIA']
if 'LASDB_STATIC_ROOT' in os.environ and os.environ['LASDB_STATIC_ROOT']:
    STATIC_ROOT = os.environ['LASDB_STATIC_ROOT']
if 'LASDB_STATIC_URL' in os.environ and os.environ['LASDB_STATIC_URL']:
    STATIC_URL = os.environ['LASDB_STATIC_URL']

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'lasDB', 'static'),
    os.path.abspath(os.path.join(BASE_DIR, os.pardir, 'webpack_src', 'lasDB', 'dist')),
)
WEBPACK_LOADER = {
    'lasDB': {
        'STATS_FILE': os.path.abspath(os.path.join(BASE_DIR, os.pardir, 'webpack_src', 'lasDB', 'webpack-stats.json')),
    }
}